### PR TITLE
feat: Consilidated blogpost sort date

### PR DESCRIPTION
**Pull request by svvimming**
Removed sortDate key in blog posts in favor of date (with proper formatting provided by forestry) for sorting

### CODE REVIEW

**Review by orvn — CHANGES_REQUESTED** [review]
@svvimming: looks good in this PR, but I merged this into `content` and PRd against `main` in #119, where the dates are out of order in the feed. Can you look into why?

Direct link to #119's preview: [bafy...zroy.on.fleek.co/explore#latest_news](https://bafybeig34ql3ow7dviw3dbvyidxmbtdqdd5iupujnqiopc6aqzyzzfzroy.on.fleek.co/explore#latest_news)

**Comment by svvimming** [comment]
> @svvimming: looks good in this PR, but I merged this into `content` and PRd against `main` in #119, where the dates are out of order in the feed. Can you look into why?
> 
> Direct link to #119's preview: [bafy...zroy.on.fleek.co/explore#latest_news](https://bafybeig34ql3ow7dviw3dbvyidxmbtdqdd5iupujnqiopc6aqzyzzfzroy.on.fleek.co/explore#latest_news)

These look in order to me? @orvn

**Comment by svvimming** [comment]
@orvn turns out blog posts appear on three pages; `blog.vue`, `explore.vue` and `index.vue`. I've updated the sort on each now so should be good

**Review by orvn — APPROVED** [review]
Amazing! Thanks @svvimming

**Pull request merged**
