### PR TITLE
feat: Accessibility improvements

### PR DESCRIPTION
**Pull request by svvimming**
Added tab accessibility for:

- navigation
- footer

### CODE REVIEW

**Comment by svvimming** [comment]
Added fixes:

- Focus ring on form on Home page
- tab accessibility for accordions
- more obvious focus rings on featured post lists

**Comment by nicole-code** [comment]
@svvimming hey-o! The accordions and the form look great and are working well! Couple of things 😄 ->

1. Concerning the addition of tab index on the nav and sub-nav - as a user, if I tab over a sub-nav section I am then unable to continue tabbing through the section from that sub-nav that I just selected. For instance, if I want to head to the Board of Directors section on the About page and I tab over Board of Directors in the sub-nav, once I am redirected to that section and I want to tab through the accordion of Board of Directors my tab order jumps back up to the nav as opposed to over the Board of Directors accordion. See screen recording for demo!

https://user-images.githubusercontent.com/67213981/193288577-58bc04f0-dd0e-4e6b-b7a6-f95d0ba564a8.mov

2. Get Involved Accordion - can we add a little bit of padding here? Just so the focus ring isn't sitting right up against the beginning of each heading?

Screen Shot 2022-09-30 at 10 12 26 AM

**Review by orvn — APPROVED** [review]
@nicole-code can you make a new ticket for @svvimming, specifically for padding considerations for outlines?

This is mergeable because that's not a blocking issue.

**Comment by nicole-code** [comment]
> @nicole-code can you make a new ticket for @svvimming, specifically for padding considerations for outlines?
> 
> This is mergeable because that's not a blocking issue.

@orvn For sure!

The padding considerations are actually being addressed in [this Notion ticket](https://www.notion.so/agencyundone/Tab-outline-should-be-consistent-across-browsers-3be1c202bd6f46c7976819821f389a9e) which is presently assigned to Sara but since other things have come up since, perhaps I should reassign to Ben just to have?

**Comment by orvn** [comment]
@nicole-code yup, you can reassign

**Pull request merged**
